name: Veracode Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # üèóÔ∏è Empaquetar el proyecto (excluyendo carpetas no necesarias)
      - name: Package source for Veracode
        run: |
          zip -r app.zip . -x ".git/*" "node_modules/*" ".github/*"

      # üì¶ Subir artefacto que usar√° Veracode
      - name: Upload artifact for Veracode
        uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: app.zip

      - name: Run Veracode Workflow Scan
        uses: veracode/github-workflow-actions@v1
        with:
          veracode_api_id: ${{ secrets.VERACODE_API_ID }}
          veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
